name: SimpleChat
description: Simple chat manager plugin for minecraft servers built on the Bukkit API.
version: 0.2-ALPHA
authors: [harry5573]
website: https://www.battlepvp.com/
main: com.battlepvp.simplechat.SimpleChat
commands:
      chat:
            aliases: [simplechat, cc]